const dbService = require('../services/dbService');
const PDFDocument = require('pdfkit');
const { ChartJSNodeCanvas } = require('chartjs-node-canvas');

class ExportController {
  async exportToPDF(req, res) {
    try {
      const { startDate, endDate } = req.query;
      
      // Get data based on date range or all data
      let query = dbService.getAllResults();
      
      if (startDate && endDate) {
        query = dbService.getResultsByDateRange(startDate, endDate);
      }
      
      const results = await query;
      
      // Create PDF document
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      
      // Set response headers
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', 'attachment; filename="qadash-report.pdf"');
      
      // Pipe the PDF to response
      doc.pipe(res);
      
      // Add header
      doc.fontSize(24)
         .fillColor('#667eea')
         .text('QADash Test Results Report', { align: 'center' });
      
      doc.moveDown();
      doc.fontSize(12)
         .fillColor('#7f8c8d')
         .text(`Generated on: ${new Date().toLocaleString('en-US')}`, { align: 'center' });
      
      doc.moveDown(2);
      
      // Calculate statistics
      const totalExecutions = results.length;
      const totalTests = results.reduce((sum, r) => sum + r.total, 0);
      const totalPassed = results.reduce((sum, r) => sum + r.passed, 0);
      const totalFailed = results.reduce((sum, r) => sum + r.failed, 0);
      const overallPassRate = totalTests > 0 ? ((totalPassed / totalTests) * 100).toFixed(2) : 0;
      
      // Add summary section
      doc.fontSize(16)
         .fillColor('#2c3e50')
         .text('Executive Summary', { underline: true });
      
      doc.moveDown();
      doc.fontSize(12)
         .fillColor('#34495e');
      
      const summaryData = [
        `Total Executions: ${totalExecutions}`,
        `Total Tests Run: ${totalTests}`,
        `Tests Passed: ${totalPassed}`,
        `Tests Failed: ${totalFailed}`,
        `Overall Pass Rate: ${overallPassRate}%`
      ];
      
      summaryData.forEach(line => {
        doc.text(line);
        doc.moveDown(0.5);
      });
      
      doc.moveDown();
      
      // Add detailed results table
      doc.addPage();
      doc.fontSize(16)
         .fillColor('#2c3e50')
         .text('Detailed Test Results', { underline: true });
      
      doc.moveDown();
      
      // Table headers
      const tableTop = doc.y;
      const colWidths = { suite: 200, framework: 80, total: 50, passed: 50, failed: 50, rate: 60 };
      let currentY = tableTop;
      
      doc.fontSize(10)
         .fillColor('#667eea')
         .font('Helvetica-Bold');
      
      doc.text('Suite Name', 50, currentY, { width: colWidths.suite });
      doc.text('Framework', 260, currentY, { width: colWidths.framework });
      doc.text('Total', 350, currentY, { width: colWidths.total });
      doc.text('Passed', 410, currentY, { width: colWidths.passed });
      doc.text('Failed', 470, currentY, { width: colWidths.failed });
      doc.text('Pass %', 530, currentY, { width: colWidths.rate });
      
      currentY += 20;
      
      // Draw header line
      doc.moveTo(50, currentY)
         .lineTo(590, currentY)
         .stroke();
      
      currentY += 10;
      
      // Table rows
      doc.font('Helvetica')
         .fillColor('#2c3e50');
      
      results.slice(0, 30).forEach((result, index) => { // Limit to 30 most recent
        if (currentY > 700) {
          doc.addPage();
          currentY = 50;
        }
        
        const passRate = result.total > 0 ? ((result.passed / result.total) * 100).toFixed(1) : 0;
        const suiteName = result.suite_name.length > 30 
          ? result.suite_name.substring(0, 27) + '...' 
          : result.suite_name;
        
        doc.fontSize(9)
           .text(suiteName, 50, currentY, { width: colWidths.suite })
           .text(result.framework || 'Unknown', 260, currentY, { width: colWidths.framework })
           .text(result.total.toString(), 350, currentY, { width: colWidths.total })
           .text(result.passed.toString(), 410, currentY, { width: colWidths.passed })
           .fillColor(result.failed > 0 ? '#e74c3c' : '#27ae60')
           .text(result.failed.toString(), 470, currentY, { width: colWidths.failed })
           .fillColor('#2c3e50')
           .text(`${passRate}%`, 530, currentY, { width: colWidths.rate });
        
        currentY += 20;
      });
      
      // Add footer
      doc.fontSize(8)
         .fillColor('#95a5a6')
         .text(
           'QADash - Professional Test Automation Dashboard | Generated by QADash',
           50,
           doc.page.height - 50,
           { align: 'center', width: doc.page.width - 100 }
         );
      
      // Finalize PDF
      doc.end();
      
    } catch (error) {
      console.error('Error exporting to PDF:', error);
      res.status(500).json({
        error: 'Failed to export PDF',
        message: error.message
      });
    }
  }

  async exportToCSV(req, res) {
    try {
      const { startDate, endDate } = req.query;
      
      // Get data based on date range or all data
      let query = dbService.getAllResults();
      
      if (startDate && endDate) {
        query = dbService.getResultsByDateRange(startDate, endDate);
      }
      
      const results = await query;
      
      // Create CSV headers
      const headers = [
        'ID', 'Suite Name', 'Framework', 'Test Type', 'Total', 'Passed', 
        'Failed', 'Pass Rate %', 'Project Category', 'Created At'
      ];
      
      // Create CSV rows
      const rows = results.map(result => {
        const passRate = result.total > 0 ? ((result.passed / result.total) * 100).toFixed(2) : 0;
        return [
          result.id,
          `"${result.suite_name}"`,
          `"${result.framework || 'Unknown'}"`,
          `"${result.test_type || 'Functional'}"`,
          result.total,
          result.passed,
          result.failed,
          passRate,
          `"${result.project_category || ''}"`,
          new Date(result.created_at).toISOString()
        ].join(',');
      });
      
      // Combine headers and rows
      const csvContent = [headers.join(','), ...rows].join('\n');
      
      // Set headers for CSV download
      res.setHeader('Content-Type', 'text/csv');
      res.setHeader('Content-Disposition', 'attachment; filename="qadash-report.csv"');
      
      res.status(200).send(csvContent);
    } catch (error) {
      console.error('Error exporting to CSV:', error);
      res.status(500).json({
        error: 'Failed to export data',
        message: error.message
      });
    }
  }
}

module.exports = new ExportController();